---
name: "Build ISO for Ublue Hyprland 43"
on:
  schedule:
    - cron: '05 12 * * 1/2'  # 12:05am UTC every two weeks on Monday
  workflow_dispatch:

jobs:
  build_iso_solopasha:
    name: "Solopasha Hyprland ISO 43"
    uses: "./.github/workflows/reusable-iso.yml"
    with:
      fedora_version: 43
      hyprland_build: solopasha
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write

  build_iso_solopasha_virt:
    name: "Solopasha Virt Hyprland ISO 43"
    uses: "./.github/workflows/reusable-iso.yml"
    with:
      fedora_version: 43
      hyprland_build: solopasha-virt
    secrets: inherit
    permissions:  
      contents: read
      packages: write
      id-token: write

  build_iso_git:
    name: "Git Hyprland ISO 43"
    uses: "./.github/workflows/reusable-iso.yml"
    with:
      fedora_version: 43
      hyprland_build: git
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
