---
name: "Build Hyprland Atomic Image 42"
on:
  schedule:
    - cron: '05 10 * * *'  # 10:05am UTC every day
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  build-fedora:
    permissions:
      contents: read
      packages: write
      id-token: write
    name: "Build Fedora 42"
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      fedora_version: 42
      hyprland_build: fedora

  build-solopasha:
    permissions:
      contents: read
      packages: write
      id-token: write
    name: "Build Solopasha 42"
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      fedora_version: 42
      hyprland_build: solopasha

  build-solopasha-virt:
    permissions:
      contents: read
      packages: write
      id-token: write
    name: "Build Solopasha Virt 42"
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      fedora_version: 42
      hyprland_build: solopasha-virt

  build-git:
    permissions:
      contents: read
      packages: write
      id-token: write
    name: "Build Git 42"
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      fedora_version: 42
      hyprland_build: git